image: node:10
stages: 
  - ESLint checks
  - Tasks testing
cache:
  paths:
   - node_modules/

before_script:
   - yarn install

ESLint check:
  stage: ESLint checks
  script: 
    - yarn lint
  only:
    refs:
      - merge_requests

Tasks testing:
  stage: Tasks testing
  script: 
    - yarn test:ci
  only:
    refs:
      - merge_requests

